services:

    Arkounay\Bundle\TwigCopyLocationBundle\DataCollector\TwigCollector:
        tags:
            -
                name:     data_collector
                template:  '@ArkounayTwigCopyLocation/data_collector/twig_template.html.twig'
                id:       'app.twig_collector'
            - { name: kernel.event_listener, event: kernel.controller }
        public: false
        arguments:
            - '@twig.profile'
            - '@twig'